@startuml 

title Arquitetura - Ingestão Planilhas Eletrônicas - Linked Service
start
:Regra STCP/SFTCP;
card "Configuração Linked Service" { 

:Linked Service ; 
:+New;
:FileSytem;
:Connection via Integration Runtime;
split

:SELFHOSTED;

kill
split again
:AZURE;
detach
split again
:SHIR-IBM;
note right
Tem acesso ao Filesystem
end note
:HOST:
USERNAME:
PASSWORD:;
note right
Usar IP evita config. STCP. 
Exemplo de host: C:/csccontainer/...
end note
end
end split

}


@enduml 