@startuml 

title JIRA - Em Verde Feito
start 

card "Captura de Dados" {
#palegreen: 01. Abertura de chamado para criação de regra STCP;
#palegreen: 02.Configuração do Linked Service no ADF;
#palegreen: 03. Configuração do Dataset genérico;
if (Notebook?) then (yes)
#palegreen: 04. Criação do Pipeline da captura de dados - Notebook Pre Landing;
else (no)
#palegreen: 04. Criação do Pipeline da captura de dados;
endif
#palegreen: 05. Mapeamento das tabelas, chaves e filtros para a tabela de controle de carga;
#palegreen: 06. Inserir registros na tabela de controle de carga ;
: 07. Teste de execução de pipeline;
: 08. Validação dos dados ma camada bronze ;
}
end

@enduml 